import type { Metadata } from "next";
import { ReactNode } from "react";
import { Poppins } from "next/font/google";
import "../globals.css";
import AccessVbucks from "@/components/AccessVbucks/AccessVbucks";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import Image from "next/image";
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600", "700"] });

export const metadata: Metadata = {
  title: "OnlyForg",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="isolate absolute h-screen -z-10 overflow-hidden bg-black">
          <Image src="/blue-bg.png" className="h-full blur-sm opacity-100  object-cover object-center" alt="reward" width={2048} height={2048}></Image>
        </div>
        <Header />
        {/* <AccessVbucks /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
